### ISSUE TITLE
Qualweb fails on URL with unicode characters: https://xn--jobsnderjylland-8tb.dk/

### ISSUE THREAD

**Issue by Tellus** [qualweb/core#13]
Hey guys,

Found another little hitch.

The site in question is https://jobsønderjylland.dk/ (or https://xn--jobsnderjylland-8tb.dk/). Our system just locks up running that URL (and its siblings), and your online evaluator immediately balks at the URLs.

I haven't had a dive into the Qualweb code itself, but my gut feeling blames the unicode characters. Any ideas?

**Comment by carlosapaduarte** [comment]
Hi!

I'm unable to open any of the urls in any browser I've tried. Can't get any response from the server, apparently due to a lack of certificate on the server. 

I've then tried opening http://jobsønderjylland.dk/ and it loaded. I've evaluated http://jobsønderjylland.dk/ on qualweb without any problem. Can you check running it without https?

**Comment by Tellus** [comment]
Hi Carlos!

Good eye. Seems like they simply don't have HTTPS activated, and I completely overlooked it.

I apologize for the inconvenience!
